Repository Harshdev625/TimeMachine, pull requests merged in 2025-10, with the labels that each got.

#6 Update Footer UI
  docs/css/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#12 Implements #11: Animated Icons for Features Section
  docs/assets/lottie/Privacy.json
  docs/assets/lottie/block.json
  docs/assets/lottie/palette.json
  docs/assets/lottie/report.json
  docs/assets/lottie/target.json
  docs/assets/lottie/timeTracker.json
  docs/css/style.css
  docs/index.html
  docs/js/main.js
  package-lock.json
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, frontend, UI/UX

#17 Added the mailer utiliity and also tested the functionality
  backend/index.js
  backend/package-lock.json
  backend/package.json
  backend/routes/auth.js
  backend/routes/mail.js
  backend/utils/resendMailer.js
Labels: hacktoberfest, hacktoberfest-accepted, backend
